// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    setUp: function(app) {
      return app.response.message = function(msg) {
        var sess;
        sess = this.req.session;
        sess.messages = sess.messages || [];
        sess.messages.push(msg);
        return this;
      };
    },
    message: function(req, res, next) {
      var msgs;
      msgs = req.session.messages || [];
      res.locals.messages = msgs;
      res.locals.hasMessages = !!msgs.length;
      /*
      		This is equivalent:
      			res.locals({
      				messages: msgs,
      				hasMessages: !! msgs.length
      			})
      */

      next();
      return req.session.messages = [];
    }
  };

}).call(this);
