// Generated by CoffeeScript 1.6.3
(function() {
  var UserSchema, authTypes, crypto, findOrCreate, mongoose, validatePresenceOf, _;

  mongoose = require('mongoose');

  crypto = require('crypto');

  _ = require('underscore');

  authTypes = [];

  UserSchema = new mongoose.Schema({
    name: {
      type: String,
      "default": ''
    },
    tags: {
      type: Array,
      "default": ''
    },
    facebookId: {
      type: String,
      "default": ''
    },
    accessToken: {
      type: String,
      "default": ''
    }
  });

  validatePresenceOf = function(value) {
    return value && value.length;
  };

  UserSchema.methods = {
    /*
    	Authenticate - check if the passwords are the same
    		@param {String} plainText
    		@return {Boolean}
    		@api public
    */

    /*
    	Make salt
    		@return {String}
    		@api public
    */

    makeSalt: function() {
      return Math.round(new Date().valueOf() * Math.random()) + "";
    },
    /*
    	Encrypt password
    		@param {String} password
    		@return {String}
    		@api public
    */

    encryptPassword: function(password) {
      var encrypred, err;
      if (!password) {
        return "";
      }
      encrypred = void 0;
      try {
        encrypred = crypto.createHmac("sha1", this.salt).update(password).digest("hex");
        return encrypred;
      } catch (_error) {
        err = _error;
        return "";
      }
    }
  };

  findOrCreate = function(schema, options) {
    return schema.statics.findOrCreate = function(conditions, doc, options, callback) {
      var self;
      if (arguments.length < 4) {
        if (typeof options === 'function') {
          callback = options;
          options = {};
        } else if (typeof doc === 'function') {
          callback = doc;
          doc = {};
          options = {};
        }
      }
      self = this;
      return this.findOne(conditions, function(err, result) {
        var key, obj, _i, _len;
        if (err || result) {
          if (options && options.upsert && !err) {
            return self.update(conditions, doc, function(err, count) {
              return self.findOne(conditions, function(err, result) {
                return callback(err, result, false);
              });
            });
          } else {
            return callback(err, result, false);
          }
        } else {
          for (_i = 0, _len = doc.length; _i < _len; _i++) {
            key = doc[_i];
            conditions[key] = doc[key];
          }
          obj = new self(conditions);
          return obj.save(function(err) {
            return callback(err, obj, true);
          });
        }
      });
    };
  };

  UserSchema.plugin(findOrCreate);

  module.exports = mongoose.model("User", UserSchema);

  console.log(module.exports.findOrCreate);

}).call(this);
