// Generated by CoffeeScript 1.6.3
(function() {
  var oauth, request, tumblr, util;

  util = require('util');

  tumblr = require('tumblr');

  oauth = require('oauth');

  request = require('request');

  require('./env.js');

  exports.sendNotification = function(user_id, template, callback) {
    var access_token, url;
    access_token = process.env.facebook_access_token;
    url = "https://graph.facebook.com/" + user_id + "/notifications?access_token=" + access_token + "&template=" + (encodeURIComponent(template));
    return request.post(url, function(error, response, body) {
      console.log("Notification request to " + url + " response:", body, error);
      return typeof callback === "function" ? callback(error, response, body) : void 0;
    });
  };

  exports.getBlog = function(blogurl) {
    var blog;
    return blog = new tumblr.Tumblr(blogurl, process.env.tumblr_ock);
  };

}).call(this);
