// Generated by CoffeeScript 1.6.3
(function() {
  var User, api, blog, blog_url, getPostsWithTags, posts, request, topics, _;

  _ = require('underscore');

  api = require('./apis.js');

  request = require('request');

  User = require('./models/user.js');

  blog_url = 'http://meavisa.tumblr.com';

  blog = api.getBlog("meavisa.tumblr.com");

  topics = [];

  posts = [];

  blog.posts(function(err, data) {
    if (err) {
      throw err;
    }
    return data.posts.forEach(function(post, i) {
      return post.tags.forEach(function(tag) {
        if (topics.indexOf(tag) === -1) {
          topics.push(tag);
          return console.log('pushing found tag', tag);
        }
      });
    });
  });

  getPostsWithTags = function(tags, callback) {
    return blog.posts({
      limit: -1
    }, function(err, data) {
      posts = [];
      data.posts.forEach(function(post) {
        var int;
        int = _.intersection(post.tags, tags);
        if (int[0]) {
          return posts.push(post);
        }
      });
      return typeof callback === "function" ? callback() : void 0;
    });
  };

  exports.Pages = {
    index: {
      get: function(req, res) {
        if (req.user) {
          req.session.messages = [JSON.stringify(req.user)];
          return getPostsWithTags(req.user.tags, function() {
            return res.render('panel', {
              user: req.user,
              topics: topics,
              posts: posts,
              blog_url: blog_url,
              messages: [JSON.stringify(req.user), JSON.stringify(req.session)]
            });
          });
        } else {
          return res.render('index');
        }
      }
    },
    logout: {
      get: function(req, res) {
        req.logout();
        return res.redirect('/');
      }
    },
    session: {
      get: function(req, res) {
        return User.find({}, function(err, users) {
          var obj;
          obj = {
            ip: req.ip,
            session: req.session,
            users: users
          };
          return res.end(JSON.stringify(obj));
        });
      }
    },
    update: {
      get: function(req, res) {
        var chosen;
        if (!req.user) {
          return res.redirect('/');
        }
        if (!req.query['topic'] || typeof req.query['topic'] === 'string') {
          req.query['topic'] = [req.query['topic']];
        }
        chosen = _.filter(req.query['topic'], function(topic) {
          return topic != null;
        });
        if (chosen && !_.isEqual(chosen, req.user.tags)) {
          api.sendNotification(req.user.facebookId, "You are following the topics " + (chosen.join(", ")) + ".");
        }
        req.user.tags = chosen;
        req.user.save();
        return getPostsWithTags(chosen, function() {
          return res.redirect('back');
        });
      }
    },
    dropall: {
      get: function(req, res) {
        var _ref;
        if (((_ref = req.user) != null ? _ref.facebookId : void 0) === "100000366187376") {
          return User.remove({}, function(err) {
            res.write("collection removed");
            return res.end(err);
          });
        } else {
          return res.end("Cannot POST /dropall");
        }
      }
    }
  };

}).call(this);
