// Generated by CoffeeScript 1.6.3
(function() {
  var Post, User, api, blog, models, mongoUri, mongoose, pushPostsToDB, _;

  _ = require('underscore');

  api = require('./api.js');

  models = require('./models/models.js');

  User = models.User;

  Post = models.Post;

  pushPostsToDB = function(blog, callback) {
    return blog.posts(function(err, data) {
      if (err) {
        if (typeof callback === "function") {
          callback(err);
        }
      }
      console.log('done');
      return callback('done');
    });
  };

  if (module === require.main) {
    mongoose = require('mongoose');
    mongoUri = process.env.MONGOLAB_URI || process.env.MONGOHQ_URL || 'mongodb://localhost/madb';
    mongoose.connect(mongoUri);
    blog = api.getBlog("meavisa.tumblr.com");
    pushPostsToDB(blog, function(err, data) {
      return mongoose.connection.close();
    });
  } else {
    exports.pushPosts = pushPostsToDB;
  }

}).call(this);
